#cloud-config
# Depends on registry (swarm can't run without registry access to pull image) bofore booting
users:
  - name: admin
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: sudo
    shell: /bin/bash
    ssh_authorized_keys:
      - ${AUTHORIZED_KEY}
package_update: true
packages:
  - vim
  - htop
  - curl
  - openssl
  - docker.io
write_files:
  - path: /etc/traefik/conf/traefik.toml
    encoding: b64
    permissions: '0644'
    content: |
      ${TRAEFIK_CONF}
  - path: /etc/traefik/tls.yml
    encoding: b64
    permissions: '0644'
    content: |
      ${TRAEFIK_TLS_CONF}
  - path: /docker-compose-traefik.yml
    encoding: b64
    permissions: '0644'
    content: |
      ${COMPOSE_TRAEFIK}
runcmd:
  - docker swarm init
  - echo "[$(date)] Swarm initialisé" >> /var/log/cloud-init.log
  - docker node ls >> /var/log/cloud-init.log
  # >>>> @TODO TEMPORARY WHILE NO PKI IS DEPLOYED >>>>
  - mkdir -p /usr/local/share/ca-certificates/${HARBOR_DOMAIN_NAME}
  - mkdir -p /etc/docker/certs.d/${HARBOR_DOMAIN_NAME}
  - |
    until openssl s_client -connect ${HARBOR_DOMAIN_NAME}:443 -showcerts </dev/null 2>/dev/null |
    openssl x509 -outform PEM > /usr/local/share/ca-certificates/${HARBOR_DOMAIN_NAME}/rootCA.crt; do
      echo "[$(date)] Registry not ready, waiting for ${HARBOR_DOMAIN_NAME}..." >> /var/log/cloud-init.log
      sleep 10
    done
  - cp /usr/local/share/ca-certificates/${HARBOR_DOMAIN_NAME}/rootCA.crt /etc/docker/certs.d/${HARBOR_DOMAIN_NAME}/ca.crt
  - update-ca-certificates
  - systemctl restart docker
  # <<<< @TODO TEMPORARY WHILE NO PKI IS DEPLOYED <<<<
  - echo "${HARBOR_ROBOT_PASSWORD}" | docker login ${HARBOR_DOMAIN_NAME} -u '${HARBOR_ROBOT_ACCOUNT}' --password-stdin
  # >>>> data specific to this network, create volume, network... >>>>
  - docker network create --driver overlay game_app_intra
  - mkdir -p /data/gameapp/db
  # <<<< data specific to this network, create volume, network... <<<<
  - echo "[$(date)] Cloud-init terminé" >> /var/log/cloud-init.log
  # <<<< TRAEFIK REVERSE PROXY PART <<<<
  # >>>> @TODO TEMPORARY WHILE NO PKI IS DEPLOYED >>>>
  # To serve HTTPS localy, traefik need a certificate
  - mkdir -p /etc/traefik/certs
  - openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/traefik/certs/local.key -out /etc/traefik/certs/local.crt -subj "/CN=*.swarm.horizon.fr"
  # <<<< @TODO TEMPORARY WHILE NO PKI IS DEPLOYED <<<<  
  - docker network create --driver overlay traefik_proxy || true
  - docker stack deploy -c /docker-compose-traefik.yml traefik
  # >>>> TRAEFIK REVERSE PROXY PART >>>>