<?xml version="1.0"?>
<opnsense>
  <version>1.0</version>
  <system>
    <hostname>opnsense</hostname>
    <domain>horizon.fr</domain>
    <group uuid="5770c607-7c72-4e54-8fe3-b87078a363d9">
      <name>admins</name>
      <description>System Administrators</description>
      <scope>system</scope>
      <gid>1999</gid>
      <member>0</member>
      <priv>page-all</priv>
    </group>
    <user uuid="fd4fea57-7106-43b0-80e3-a921f2f8dd8b">
      <name>root</name>
      <descr>System Administrator</descr>
      <scope>system</scope>
      <group>admins</group>
      <password>${OPNSENSE_ADMIN_PASSWORD}</password>
      <uid>0</uid>
    </user>
    <webgui>
      <protocol>https</protocol>
    </webgui>
  </system>
  <OPNsense>
    <Firewall>
      <Alias version="1.0.1" description="Firewall aliases">
        <geoip>
          <url/>
        </geoip>
        <aliases>
          <alias uuid="303c1524-4862-4ae7-bd2d-d7403747d961">
            <enabled>1</enabled>
            <name>private_networks</name>
            <type>network</type>
            <content>10.0.0.0/8
172.16.0.0/12
192.168.0.0/16</content>
            <description>Private address ranges</description>
          </alias>
          <alias uuid="8509b092-747e-4218-8fdb-ce20f8db9087">
            <enabled>1</enabled>
            <name>ceph_client_ports</name>
            <type>port</type>
            <content>3300
6789
6800:7300</content>
            <description>Ceph client ports: mon (msgr2/msgr1) + OSD range</description>
          </alias>
        </aliases>
      </Alias>
    </Firewall>
  </OPNsense>
  <interfaces>
    <wan>
      <if>vtnet0</if>
      <descr>WAN</descr>
      <enable>1</enable>
      <ipaddr>dhcp</ipaddr>
      <ipaddrv6>dhcp6</ipaddrv6>
      <blockpriv>0</blockpriv>
      <blockbogons>1</blockbogons>
    </wan>
    <opt3>
      <if>vtnet4</if>
      <descr>DMZ</descr>
      <enable>1</enable>
      <ipaddr>192.168.122.1</ipaddr>
      <subnet>27</subnet>
    </opt3>
    <opt1>
      <if>vtnet1</if>
      <descr>USER</descr>
      <enable>1</enable>
      <ipaddr>10.0.99.1</ipaddr>
      <subnet>24</subnet>
    </opt1>
    <lan>
      <if>vtnet2</if>
      <descr>ADMIN</descr>
      <enable>1</enable>
      <ipaddr>10.0.100.1</ipaddr>
      <subnet>24</subnet>
    </lan>
    <opt4>
      <if>vtnet3_vlan10</if>
      <descr>HARBOR</descr>
      <enable>1</enable>
      <ipaddr>10.0.110.1</ipaddr>
      <subnet>24</subnet>
    </opt4>
    <opt5>
      <if>vtnet3_vlan20</if>
      <descr>CEPH</descr>
      <enable>1</enable>
      <ipaddr>10.0.120.1</ipaddr>
      <subnet>24</subnet>
    </opt5>
    <opt6>
      <if>vtnet3_vlan30</if>
      <descr>SWARM</descr>
      <enable>1</enable>
      <ipaddr>10.0.130.1</ipaddr>
      <subnet>24</subnet>
    </opt6>
    <opt7>
      <if>vtnet3_vlan40</if>
      <descr>IDS</descr>
      <enable>1</enable>
      <ipaddr>10.0.140.1</ipaddr>
      <subnet>24</subnet>
    </opt7>
  </interfaces>
  <vlans version="1.0.0" description="VLAN configuration">
    <vlan>
      <if>vtnet3</if>
      <tag>10</tag>
      <vlanif>vtnet3_vlan10</vlanif>
      <descr>HARBOR</descr>
    </vlan>
    <vlan>
      <if>vtnet3</if>
      <tag>20</tag>
      <vlanif>vtnet3_vlan20</vlanif>
      <descr>CEPH</descr>
    </vlan>
    <vlan>
      <if>vtnet3</if>
      <tag>30</tag>
      <vlanif>vtnet3_vlan30</vlanif>
      <descr>SWARM</descr>
    </vlan>
    <vlan>
      <if>vtnet3</if>
      <tag>40</tag>
      <vlanif>vtnet3_vlan40</vlanif>
      <descr>IDS</descr>
    </vlan>
  </vlans>
  <dnsmasq version="1.0.9" description="Dnsmasq DNS and DHCP">
    <enable>1</enable>
    <regdhcp>0</regdhcp>
    <regdhcpstatic>0</regdhcpstatic>
    <dhcpfirst>0</dhcpfirst>
    <strict_order>0</strict_order>
    <domain_needed>0</domain_needed>
    <no_private_reverse>0</no_private_reverse>
    <no_resolv>0</no_resolv>
    <log_queries>0</log_queries>
    <no_hosts>0</no_hosts>
    <strictbind>0</strictbind>
    <dnssec>0</dnssec>
    <regdhcpdomain/>
    <interface>lan</interface>
    <port>53053</port>
    <dns_forward_max/>
    <cache_size/>
    <local_ttl/>
    <add_mac/>
    <add_subnet>0</add_subnet>
    <strip_subnet>0</strip_subnet>
    <dhcp>
      <no_interface/>
      <fqdn>1</fqdn>
      <domain/>
      <local>1</local>
      <lease_max/>
      <authoritative>0</authoritative>
      <default_fw_rules>1</default_fw_rules>
      <reply_delay/>
      <enable_ra>0</enable_ra>
      <host_ping>1</host_ping>
      <nosync>0</nosync>
      <log_dhcp>0</log_dhcp>
      <log_quiet>0</log_quiet>
    </dhcp>
    <no_ident>1</no_ident>
    <dhcp_ranges uuid="1a2b3c4d-1111-4a11-8a11-100000000001">
      <interface>lan</interface>
      <set_tag/>
      <start_addr>10.0.100.100</start_addr>
      <end_addr>10.0.100.200</end_addr>
      <subnet_mask/>
      <constructor/>
      <mode/>
      <prefix_len/>
      <lease_time/>
      <domain_type>range</domain_type>
      <domain/>
      <nosync>0</nosync>
      <ra_mode/>
      <ra_priority/>
      <ra_mtu/>
      <ra_interval/>
      <ra_router_lifetime/>
      <description>ADMIN</description>
    </dhcp_ranges>
    <dhcp_ranges uuid="1a2b3c4d-2222-4a11-8a11-100000000002">
      <interface>opt1</interface>
      <set_tag/>
      <start_addr>10.0.99.100</start_addr>
      <end_addr>10.0.99.200</end_addr>
      <subnet_mask/>
      <constructor/>
      <mode/>
      <prefix_len/>
      <lease_time/>
      <domain_type>range</domain_type>
      <domain/>
      <nosync>0</nosync>
      <ra_mode/>
      <ra_priority/>
      <ra_mtu/>
      <ra_interval/>
      <ra_router_lifetime/>
      <description>USER</description>
    </dhcp_ranges>
  </dnsmasq>
  <nat>
    <outbound>
      <mode>automatic</mode>
    </outbound>
    <rule uuid="eb227843-d0ff-4793-9f14-8b79fbb8e1d7">
      <sequence>100</sequence>
      <disabled>0</disabled>
      <nordr>0</nordr>
      <interface>wan</interface>
      <ipprotocol/>
      <protocol>tcp</protocol>
      <source>
        <network/>
        <port/>
        <not>0</not>
      </source>
      <destination>
        <network>wanip</network>
        <port>80</port>
        <not>0</not>
      </destination>
      <target>192.168.122.13</target>
      <local-port>80</local-port>
      <poolopts/>
      <log>0</log>
      <category/>
      <descr>DNAT HTTP - swarm VIP</descr>
      <tag/>
      <tagged/>
      <nosync>0</nosync>
      <natreflection/>
      <pass/>
      <associated-rule-id>nat_80</associated-rule-id>
      <created>
        <username/>
        <time/>
        <description/>
      </created>
      <updated>
        <username/>
        <time/>
        <description/>
      </updated>
    </rule>
    <rule uuid="88deef91-08ed-40b3-b3ef-4002c451237f">
      <sequence>200</sequence>
      <disabled>0</disabled>
      <nordr>0</nordr>
      <interface>wan</interface>
      <ipprotocol/>
      <protocol>tcp</protocol>
      <source>
        <network/>
        <port/>
        <not>0</not>
      </source>
      <destination>
        <network>wanip</network>
        <port>443</port>
        <not>0</not>
      </destination>
      <target>192.168.122.13</target>
      <local-port>443</local-port>
      <poolopts/>
      <log>0</log>
      <category/>
      <descr>DNAT HTTPS - swarm VIP</descr>
      <tag/>
      <tagged/>
      <nosync>0</nosync>
      <natreflection/>
      <pass/>
      <associated-rule-id>nat_443</associated-rule-id>
      <created>
        <username/>
        <time/>
        <description/>
      </created>
      <updated>
        <username/>
        <time/>
        <description/>
      </updated>
    </rule>
  </nat>
  <filter>
    <rule>
      <id>nat_80</id>
      <type>pass</type>
      <interface>wan</interface>
      <protocol>tcp</protocol>
      <source><any>1</any></source>
      <destination>
        <address>192.168.122.13</address>
        <port>80</port>
      </destination>
      <descr>Allow forwarded HTTP to swarm VIP</descr>
    </rule>
    <rule>
      <id>nat_443</id>
      <type>pass</type>
      <interface>wan</interface>
      <protocol>tcp</protocol>
      <source><any>1</any></source>
      <destination>
        <address>192.168.122.13</address>
        <port>443</port>
      </destination>
      <descr>Allow forwarded HTTPS to swarm VIP</descr>
    </rule>
    <!-- TEMPORAIRE : accès direct au webGUI depuis le WAN, le temps de
         configurer WireGuard. À retirer une fois le VPN opérationnel. -->
    <rule>
      <type>pass</type>
      <interface>wan</interface>
      <protocol>tcp</protocol>
      <source><any>1</any></source>
      <destination>
        <network>wanip</network>
        <port>443</port>
      </destination>
      <descr>TEMP - Allow WAN to webGUI (remove after WireGuard setup)</descr>
    </rule>
    <rule>
      <type>block</type>
      <interface>wan</interface>
      <ipprotocol>inet</ipprotocol>
      <source><any>1</any></source>
      <destination><any>1</any></destination>
      <log>1</log>
      <descr>Deny all other WAN traffic</descr>
    </rule>
    <rule>
      <type>pass</type>
      <interface>opt4</interface>
      <ipprotocol>inet</ipprotocol>
      <source><network>opt4</network></source>
      <destination><network>opt6</network></destination>
      <descr>Allow HARBOR - SWARM</descr>
    </rule>
    <rule>
      <type>pass</type>
      <interface>opt6</interface>
      <protocol>tcp</protocol>
      <ipprotocol>inet</ipprotocol>
      <source><network>opt6</network></source>
      <destination>
        <network>opt4</network>
        <port>443</port>
      </destination>
      <descr>Allow SWARM - HARBOR (registry pulls, HTTPS only)</descr>
    </rule>
    <rule>
      <type>pass</type>
      <interface>opt5</interface>
      <ipprotocol>inet</ipprotocol>
      <source><network>opt5</network></source>
      <destination><network>opt6</network></destination>
      <descr>Allow CEPH - SWARM</descr>
    </rule>
    <rule>
      <type>pass</type>
      <interface>opt6</interface>
      <protocol>tcp</protocol>
      <ipprotocol>inet</ipprotocol>
      <source><network>opt6</network></source>
      <destination>
        <network>opt5</network>
        <port>ceph_client_ports</port>
      </destination>
      <descr>Allow SWARM - CEPH (client I/O: mon 3300/6789, OSD 6800:7300)</descr>
    </rule>
    <!-- ADMIN is fully trusted: explicit full access to every internal
         zone (br-user, br-server's three VLANs, br-dmz) rather than the
         narrow dashboard-only rule this used to be -->
    <rule>
      <type>pass</type>
      <interface>lan</interface>
      <ipprotocol>inet</ipprotocol>
      <source><network>lan</network></source>
      <destination><network>opt1</network></destination>
      <descr>Allow ADMIN - USER (br-user)</descr>
    </rule>
    <rule>
      <type>pass</type>
      <interface>lan</interface>
      <ipprotocol>inet</ipprotocol>
      <source><network>lan</network></source>
      <destination><network>opt4</network></destination>
      <descr>Allow ADMIN - HARBOR (br-server)</descr>
    </rule>
    <rule>
      <type>pass</type>
      <interface>lan</interface>
      <ipprotocol>inet</ipprotocol>
      <source><network>lan</network></source>
      <destination><network>opt5</network></destination>
      <descr>Allow ADMIN - CEPH (br-server)</descr>
    </rule>
    <rule>
      <type>pass</type>
      <interface>lan</interface>
      <ipprotocol>inet</ipprotocol>
      <source><network>lan</network></source>
      <destination><network>opt6</network></destination>
      <descr>Allow ADMIN - SWARM (br-server)</descr>
    </rule>
    <rule>
      <type>pass</type>
      <interface>lan</interface>
      <ipprotocol>inet</ipprotocol>
      <source><network>lan</network></source>
      <destination><network>opt7</network></destination>
      <descr>Allow ADMIN - IDS (br-server)</descr>
    </rule>
    <rule>
      <type>pass</type>
      <interface>lan</interface>
      <ipprotocol>inet</ipprotocol>
      <source><network>lan</network></source>
      <destination><network>opt3</network></destination>
      <descr>Allow ADMIN - DMZ (br-dmz)</descr>
    </rule>
    <rule>
      <type>block</type>
      <interface>opt4</interface>
      <ipprotocol>inet</ipprotocol>
      <source><network>opt4</network></source>
      <destination><network>private_networks</network></destination>
      <descr>Block HARBOR - private_networks</descr>
    </rule>
    <rule>
      <type>pass</type>
      <interface>opt4</interface>
      <ipprotocol>inet</ipprotocol>
      <source><network>opt4</network></source>
      <destination><any>1</any></destination>
      <descr>Allow HARBOR  to WAN</descr>
    </rule>
    <rule>
      <type>block</type>
      <interface>opt5</interface>
      <ipprotocol>inet</ipprotocol>
      <source><network>opt5</network></source>
      <destination><network>private_networks</network></destination>
      <descr>Block CEPH - private_networks </descr>
    </rule>
    <rule>
      <type>pass</type>
      <interface>opt5</interface>
      <ipprotocol>inet</ipprotocol>
      <source><network>opt5</network></source>
      <destination><any>1</any></destination>
      <descr>Allow CEPH  to WAN</descr>
    </rule>
    <rule>
      <type>block</type>
      <interface>opt7</interface>
      <ipprotocol>inet</ipprotocol>
      <source><network>opt7</network></source>
      <destination><network>private_networks</network></destination>
      <descr>Block IDS - private_networks</descr>
    </rule>
    <rule>
      <type>pass</type>
      <interface>opt7</interface>
      <ipprotocol>inet</ipprotocol>
      <source><network>opt7</network></source>
      <destination><any>1</any></destination>
      <descr>Allow IDS to WAN</descr>
    </rule>
    <rule>
      <type>block</type>
      <interface>opt1</interface>
      <ipprotocol>inet</ipprotocol>
      <source><network>opt1</network></source>
      <destination><network>private_networks</network></destination>
      <descr>Block USER - private_networks </descr>
    </rule>
    <rule>
      <type>pass</type>
      <interface>opt1</interface>
      <ipprotocol>inet</ipprotocol>
      <source><network>opt1</network></source>
      <destination><any>1</any></destination>
      <descr>Allow USER (br-user)  to WAN</descr>
    </rule>
    <rule>
      <type>block</type>
      <interface>lan</interface>
      <ipprotocol>inet</ipprotocol>
      <source><network>lan</network></source>
      <destination><network>private_networks</network></destination>
      <descr>Block ADMIN - private_networks</descr>
    </rule>
    <rule>
      <type>pass</type>
      <interface>lan</interface>
      <ipprotocol>inet</ipprotocol>
      <source><network>lan</network></source>
      <destination><any>1</any></destination>
      <descr>Allow ADMIN  to WAN</descr>
    </rule>
  </filter>
</opnsense>
