#cloud-config
# Depends on swarm manager before booting
users:
  - name: admin
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: sudo
    shell: /bin/bash
    ssh_authorized_keys:
      - ${AUTHORIZED_KEY}
package_update: true
packages:
  - vim
  - htop
  - curl
  - docker.io
runcmd:
  - "until docker swarm join --token ${SWARM_TOKEN_WORKER}; do echo \"[$(date)] Swarm join failed, retrying...\"  >> /var/log/cloud-init.log; sleep 5; done" 
  - echo "[$(date)] Swarm initialisé" >> /var/log/cloud-init.log
  - docker node ls >> /var/log/cloud-init.log
  - echo "[$(date)] Cloud-init terminé" >> /var/log/cloud-init.log