network:
  version: 2
  renderer: networkd
  ethernets:
    enp1s0f0:
      match:
        macaddress: 0c:c4:7a:85:82:66
      dhcp4: false
      dhcp6: false
      set-name: "enp1s0f0"
      macaddress: 6e:69:8e:a0:73:77
  bridges:
    br-wan:
      interfaces: [enp1s0f0]
      dhcp4: false
      dhcp6: false
      macaddress: 16:0c:55:5d:9f:82
    br-user:
      dhcp4: false
      dhcp6: false
      openvswitch: {}
    # 10.0.100.0/24 gateway is OPNsense's ADMIN leg (10.0.100.1)
    br-admin:
      dhcp4: false
      dhcp6: false
      addresses: [10.0.100.2/24]
      routes:
        - to: default
          via: 10.0.100.1
      nameservers:
        addresses: [10.0.100.1]
      openvswitch: {}
    # 192.168.122.0/27 gateway is OPNsense's DMZ leg (192.168.122.1)
    br-dmz:
      dhcp4: false
      dhcp6: false
      openvswitch: {}
    br-server:
      dhcp4: false
      dhcp6: false
      openvswitch: {}
