#cloud-config
users:
  - name: admin
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: sudo
    shell: /bin/bash
    ssh_authorized_keys:
      - ${AUTHORIZED_KEY}
package_update: true
packages:
  - vim
  - htop
  - wget
  - openssl
  - docker.io
  - docker-compose
write_files:
  - path: /opt/harbor/harbor.yml
    encoding: b64
    permissions: '0644'
    content: |
      ${HARBOR_CONFIG}
runcmd:
  # create data directory to preserve image even though harbor is shutdown
  - mkdir /data
  # create certs directory
  - mkdir -p /opt/harbor/certs
  # >>>> FOR LAB ONLY (WILL USE A PKI LATER) >>>>
  - openssl req -x509 -newkey ec -pkeyopt ec_paramgen_curve:prime256v1 -keyout /opt/harbor/certs/server.key -out /opt/harbor/certs/server.crt -days 365 -nodes -subj "/CN=${HARBOR_DOMAIN_NAME}" -addext "subjectAltName=DNS:${HARBOR_DOMAIN_NAME}"
  # <<<< FOR LAB ONLY (WILL USE A PKI LATER) <<<<<
  - wget https://github.com/goharbor/harbor/releases/download/v2.15.2/harbor-offline-installer-v2.15.2.tgz -O /opt/harbor-offline-installer-v2.15.2.tgz
  - cd /opt && tar xzvf ./harbor-offline-installer-v2.15.2.tgz
  - echo "[$(date)] Harbor téléchargé et installé" >> /var/log/cloud-init.log
  - cd /opt/harbor && ./install.sh --with-trivy
  - echo "[$(date)] Harbor est en cours d'exécution" >> /var/log/cloud-init.log